# .github/workflows/ci.yml
name: CI - Tests Unitaires SSL/TLS Scanner

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  test:
    name: Exécuter les Tests Unitaires
    runs-on: ubuntu-22.04  # Utilise une version stable d'Ubuntu
    timeout-minutes: 15

    strategy:
      matrix:
        python-version: [3.8, 3.9]  # Exécute les tests sur plusieurs versions de Python

    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: false

    steps:
    - name: Nettoyer le cache de GitHub Actions
      uses: geekyeggo/delete-artifact@v2
      with:
        name: python
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Debug - Afficher les versions de Python disponibles
      run: ls /opt/hostedtoolcache/Python

    - name: Installer Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4  # Version stable
      with:
        python-version: ${{ matrix.python-version }}

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Exécuter les tests unitaires
      run: pytest tests/ --tb=short --maxfail=3 -v

